### ISSUE TITLE
New feature: Rerun workflow

### ISSUE THREAD

**Issue by sirspock** [KnowledgeCaptureAndDiscovery/wings#105]
**Is your feature request related to a problem? Please describe.**

If a workflow fails then I must fill the parameters and data again.

**Describe the solution you'd like**
A button called "Re run" on the My runs view

**Comment by sirspock** [comment]
@varunratnakar You know the system. How hard is it to do this? I wanna do it.

**Comment by sirspock** [comment]
I think it's not complex

**Comment by varunratnakar** [comment]
Shouldn't be hard to do

-------- Original Message --------
Subject: Re: [KnowledgeCaptureAndDiscovery/wings] New feature: Rerun workflow (#105)
From: Maximiliano Osorio
To: KnowledgeCaptureAndDiscovery/wings
CC: Varun Ratnakar ,Mention


@varunratnakar<https://github.com/varunratnakar> You know the system. How hard is it to do this? I wanna do it.
