### ISSUE TITLE
Change DockerHub images to GitHub registry

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/wings#152]
DockerHub now requires a paid subscription for open source organizations. I suggest start moving images to the GitHub registry, which is free (for now).  DockerHub opensource organizations will be deleted (along with their images) in the upcoming months
This can be done through an action. Here is an example that could serve as inspiration: https://github.com/dgarijo/Widoco/blob/master/.github/workflows/ci.yml

**Comment by mosoriob** [comment]
OMG!
