### ISSUE TITLE
It is difficult to add categories and abstract components in the root level

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/wings#31]
I have created a new domain. Whenever I add a new component type, I must close all the other ones I have created before, otherwise it will create a component under the last selected one. 
That is, if I select a component I can't deselect it without having to close its corresponding window.

I wonder if it would be possible to move components by clicking and dragging them in the hierarchy.

**Comment by IKCAP** [comment]
http://www.opmw.org/4.0 <http://www.opmw.org/4.0>

Should redirect to http://seagull.isi.edu:3030 <http://seagull.isi.edu:3030/>

**Comment by dgarijo** [comment]
I think the answer does not belong to this particular issue, but thanks a lot for the response :)

**Comment by IKCAP** [comment]
Whoops, sorry about that !
