### ISSUE TITLE
Logging in and out leads to 404

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/wings#40]
How to reproduce this error:
* Log in with a user.
* Log out.
* Try to log in again with the previous user. 
* The page remains the same when clicking ok. If you click again, you will see a 404: HTTP Status 404 - /wings-portal/j_security_check

If you reload http://wings-workflows.org/wings-portal/ you will see the portal logged in fine.

**Comment by IKCAP** [comment]
Thanks for the bug report Daniel. I've committed a fix for this
https://github.com/IKCAP/wings/commit/3ee9fc9599d42fbed7642b0ea99d35381c2e4a58

(Needs to be tested)

**Comment by sirspock** [comment]
Test: ok
