### ISSUE TITLE
Maven install failure due to unavailable resources

### ISSUE THREAD

**Issue by juan-vg** [KnowledgeCaptureAndDiscovery/wings#41]
How to reproduce this error:

    $ git clone https://github.com/IKCAP/wings
    $ cd wings
    $ maven install

`[ERROR] Failed to execute goal on project wings-ontapi: Could not resolve dependencies for project edu.isi.wings:wings-ontapi:jar:4.0-SNAPSHOT: Failed to collect dependencies at com.clarkparsia.pellet:pellet-jena:jar:2.4.0-SNAPSHOT: Failed to read artifact descriptor for com.clarkparsia.pellet:pellet-jena:jar:2.4.0-SNAPSHOT: Could not transfer artifact com.clarkparsia.pellet:pellet-jena:pom:2.4.0-SNAPSHOT from/to Local archiva.snapshots repository (http://www.wings-workflows.org/archiva/repository/snapshots/): Failed to transfer file: http://www.wings-workflows.org/archiva/repository/snapshots/com/clarkparsia/pellet/pellet-jena/2.4.0-SNAPSHOT/pellet-jena-2.4.0-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Temporarily Unavailable. -> [Help 1]`

**Comment by IKCAP** [comment]
The archiva repository server was down. Thanks for letting us know Juan. I've restarted it now. Please let me know if it works now.

**Comment by juan-vg** [comment]
Everything OK! Thank you very much :)
