### ISSUE TITLE
BUILD FAILURE !! when mvn install

### ISSUE THREAD

**Issue by alaasamameer** [KnowledgeCaptureAndDiscovery/wings#61]
Greetings,
if I  

$ git clone https://github.com/IKCAP/wings
$ cd wings
$ mvn install

I git 

[INFO] Building Wings Planner 4.0-SNAPSHOT
[INFO] -------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ wings-planner ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /opt/wings/planner/src/main/resources
[INFO] Copying 66 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ wings-planner ---
[INFO] Compiling 120 source files to /opt/wings/planner/target/classes
[INFO] -----------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Wings Core ...................... SUCCESS [  0.332 s]
[INFO] Wings Ontology API .......... SUCCESS [  1.246 s]
[INFO] Wings Planner.............. FAILURE [  0.855 s]
[INFO] Wings OPM Mapper ................ SKIPPED
[INFO] Wings Portal................ SKIPPED
[INFO] Wings ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.683 s
[INFO] Finished at: 2017-10-12T20:43:20Z
[INFO] Final Memory: 10M/26M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project wings-planner: Compilation failure: Compilation failure:
[ERROR] /opt/wings/planner/src/main/java/edu/isi/wings/common/logging/Escape.java:[53,20] error: unmappable character for encoding ASCII
[ERROR]
[ERROR] /opt/wings/planner/src/main/java/edu/isi/wings/common/logging/Escape.java:[53,21] error: unmappable character for encoding ASCII
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :wings-planner

what is the problem ? and how to solve ? plz step by step

**Comment by dgarijo** [comment]
Thanks for leaving the issue. We will look into it. @varunratnakar  could there be an error in some of the logging files?

In the meantime, if you just want to reuse WINGS and deploy it on your machine, you can pull one of our docker images: https://hub.docker.com/r/kcapd/wings-base/ You may find instructions here: https://github.com/KnowledgeCaptureAndDiscovery/wings-docker

**Comment by varunratnakar** [comment]
Try setting this before doing an mvn install:
export MAVEN_OPTS= -Dfile.encoding=UTF-8

**Comment by alaasamameer** [comment]
thanks a lot for you all @dgarijo @varunratnakar, it's work, after ( export MAVEN_OPTS= -Dfile.encoding="UTF-8" ) as @varunratnakar advised me 
I am student and I try to setup it directly to Ubuntu machine according to my study and academic research requirements
[INFO] Packaging webapp
[INFO] Assembling webapp [wings-portal] in [/opt/wings/portal/target/wings-portal-4.0-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp resources [/opt/wings/portal/src/main/webapp]
[INFO] Webapp assembled in [1279 msecs]
[INFO] Building war: /opt/wings/portal/target/wings-portal-4.0-SNAPSHOT.war
[INFO] WEB-INF/web.xml already added, skipping
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ wings-portal ---
[INFO] Installing /opt/wings/portal/target/wings-portal-4.0-SNAPSHOT.war to /root/.m2/repository/edu/isi/wings/wings-portal/4.0-SNAPSHOT/wings-portal-4.0-SNAPSHOT.war
[INFO] Installing /opt/wings/portal/pom.xml to /root/.m2/repository/edu/isi/wings/wings-portal/4.0-SNAPSHOT/wings-portal-4.0-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Wings 4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ wings ---
[INFO] Installing /opt/wings/pom.xml to /root/.m2/repository/edu/isi/wings/wings/4.0-SNAPSHOT/wings-4.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Wings Core ......................................... SUCCESS [ 10.040 s]
[INFO] Wings Ontology API ................................. SUCCESS [01:12 min]
[INFO] Wings Planner ...................................... SUCCESS [ 17.592 s]
[INFO] Wings OPM Mapper ................................... SUCCESS [  6.555 s]
[INFO] Wings Portal ....................................... SUCCESS [01:20 min]
[INFO] Wings .............................................. SUCCESS [  0.130 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:07 min
[INFO] Finished at: 2017-10-13T17:00:22Z
[INFO] Final Memory: 65M/156M
[INFO] ------------------------------------------------------------------------

**Comment by dgarijo** [comment]
I updated the readme file addressing this error

**Comment by alaasamameer** [comment]
thanks a lot
