### ISSUE TITLE
[ERROR] !! when installing with Pegasus options

### ISSUE THREAD

**Issue by alaasamameer** [KnowledgeCaptureAndDiscovery/wings#62]
**Best Greetings : 
I follow your instructions in :**

https://github.com/KnowledgeCaptureAndDiscovery/wings/tree/1098e9b299d9a001676f2e17d07deaabb4632542/engines/pegasus

**but I got this errors:**

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Wings Core ......................................... SUCCESS [  8.807 s]
[INFO] Wings Ontology API ................................. FAILURE [ 37.855 s]
[INFO] Wings Planner ...................................... SKIPPED
[INFO] Wings OPM Mapper ................................... SKIPPED
[INFO] Wings Pegasus Engine ............................... SKIPPED
[INFO] Wings Pegasus Adapter .............................. SKIPPED
[INFO] Wings Portal ....................................... SKIPPED
[INFO] Wings .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.898 s
[INFO] Finished at: 2017-11-04T13:42:08Z
[INFO] Final Memory: 11M/26M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wings-ontapi: Could not resolve dependencies for project edu.isi.wings:wings-ontapi:jar:4.0-SNAPSHOT: Failed to collect dependencies at com.clarkparsia.pellet:pellet-jena:jar:2.4.0-SNAPSHOT: Fail
ed to read artifact descriptor for com.clarkparsia.pellet:pellet-jena:jar:2.4.0-SNAPSHOT: Could not transfer artifact com.clarkparsia.pellet:pellet-jena:pom:2.4.0-SNAPSHOT from/to Local archiva.snapshots repository (http://www.wings-work
flows.org/archiva/repository/snapshots/): Failed to transfer file: http://www.wings-workflows.org/archiva/repository/snapshots/com/clarkparsia/pellet/pellet-jena/2.4.0-SNAPSHOT/pellet-jena-2.4.0-SNAPSHOT.pom. Return code is: 503 , Reason
Phrase:Service Temporarily Unavailable. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :wings-ontapi

**Can you please guide me to solve this problem step by step ?**

**Comment by mayani** [comment]
1. Unable to recreate this. Issue may have been due to issue with Maven repo. 
2. There was another issue where build failed on first mvn install, but worked if mvn install was re-executed. Fixed that issue with commit #37c78b72def51da00dc1c083a29c1ffe019b93a0
