### ISSUE TITLE
A problem when use with Pegasus, Submitting jobs as user/group 0 (root) is not allowed, and when run as user functions not work!!!

### ISSUE THREAD

**Issue by alaasamameer** [KnowledgeCaptureAndDiscovery/wings#63]
**Greetings,**

**A problem when use with Pegasus, Submitting jobs as user/group 0 (root) is not allowed, and when running tomcat as user many functions not work such as editing components code and others !!! what is the solutions ?? if you can, please step by step**

**part of log:**

`
17.11.16 06:40:59.341 UTC:   Log of the life of condor_dagman itself          : histogram-44a0b5-81d1dfe8-ca3d-4d00-87ec-dd6a7160243b-0.dag.dagman.log 
2017.11.16 06:40:59.347 UTC:    
2017.11.16 06:40:59.363 UTC:   ----------------------------------------------------------------------- 
2017.11.16 06:40:59.377 UTC: [INFO] event.pegasus.code.generation dax.id histogram-44a0b5-81d1dfe8-ca3d-4d00-87ec-dd6a7160243b_0  (0.25 seconds) - FINISHED 
2017.11.16 06:41:02.492 UTC:   Created Pegasus database in: sqlite:////opt/tomcat/wings-storage/histogram-44a0b5-81d1dfe8-ca3d-4d00-87ec-dd6a7160243b/master.db 
2017.11.16 06:41:02.498 UTC:   Your database is compatible with Pegasus version: 4.8.0 
2017.11.16 06:41:02.630 UTC:   Submitting to condor histogram-44a0b5-81d1dfe8-ca3d-4d00-87ec-dd6a7160243b-0.dag.condor.sub 
2017.11.16 06:41:02.637 UTC: [ERROR]   
2017.11.16 06:41:02.642 UTC: [ERROR]  ERROR: Submitting jobs as user/group 0 (root) is not allowed for security reasons. 
2017.11.16 06:41:02.648 UTC: [ERROR]  ERROR: Running condor_submit /usr/bin/condor_submit histogram-44a0b5-81d1dfe8-ca3d-4d00-87ec-dd6a7160243b-0.dag.condor.sub failed with exit code 1 at /usr/bin/pegasus-run line 327. 
2017.11.16 06:41:02.654 UTC: [FATAL ERROR]  java.lang.RuntimeException: Unable to submit the workflow using pegasus-run
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:695)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:364)
	at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:245)
 
2017.11.16 06:41:07.688 UTC: [INFO] event.pegasus.planner planner.version 4.8.0  (9.806 seconds) - FINISHED 

`

**Comment by AshishPandey90** [comment]
Hey, did you get this resolved. I am facing similar issue.

9.04.13 17:43:02.551 PDT: [ERROR]   
2019.04.13 17:43:02.559 PDT: [ERROR]  ERROR: Submitting jobs as user/group 0 (root) is not allowed for security reasons. 
2019.04.13 17:43:02.568 PDT: [ERROR]  ERROR: Running condor_submit /usr/bin/condor_submit process-0.dag.condor.sub failed with exit code 1 at /usr/bin/pegasus-run line 327. 
2019.04.13 17:43:02.575 PDT: [FATAL ERROR]  
 [1] java.lang.RuntimeException: Unable to submit the workflow using pegasus-run at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:697)

**Comment by mayani** [comment]
Pegasus uses HTCondor as a scheduler. HTCondor does not allow submitting workflows as root. 

Being unable to edit components etc. while running as user tomcat is likely related to file system permissions on the WINGS related files i.e. They have rw permissions for user root and not user tomcat. Verify file permissions on WINGS storage dir.
