### ISSUE TITLE
Error when running WINGS in mac from docker image

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/wings#66]
Whenever you try to access WINGS component catalog and you click on the component files, the interface will break, making you unable to edit a script or a run file. The only way of uploading components is through the upload button.

I have been able to reproduce this error in two different mac computers when executing any of our docker images. This error **does not** appear in Windows or Linux systems. It looks like some of the content is being blocked for a reason: 

![error](https://user-images.githubusercontent.com/1520666/38704530-7c9d08b4-3e5b-11e8-93c0-7c3adedc5e44.png)

The page won't work after reloading and after having disabled firewalls, etc.

**Comment by dgarijo** [comment]
More information about the error in the console:
![pastedgraphic-2](https://user-images.githubusercontent.com/1520666/39896212-13c17ea2-5462-11e8-90b4-510a28793ba2.png)

**Comment by varunratnakar** [comment]
This was fixed with commit: 3c3c77b
Codemirror library was being deleted on maven clean. If we create a fresh docker image with the latest wings, it should be fine.

**Comment by dgarijo** [comment]
Thanks! Could you please update the docker hub images? In the future, having something like this: https://docs.docker.com/docker-hub/builds/ could help making the process automatic.

**Comment by varunratnakar** [comment]
I've updated kcapd/wings-base

On 11 May 2018, at 07:08, Daniel Garijo <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! Could you please update the docker hub images? In the future, having something like this: https://docs.docker.com/docker-hub/builds/ could help making the process automatic.

**Comment by varunratnakar** [comment]
Actually it is built, but still pushing.. Will take a while to push it on the repo.


On 11 May 2018, at 11:19, Varun Ratnakar <varunr@isi.edu<mailto:varunr@isi.edu>> wrote:

I've updated kcapd/wings-base

On 11 May 2018, at 07:08, Daniel Garijo <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! Could you please update the docker hub images? In the future, having something like this: https://docs.docker.com/docker-hub/builds/ could help making the process automatic.

**Comment by dgarijo** [comment]
Thanks, Varun.
I will close the issue then :)
