### ISSUE TITLE
Automate WINGS docker image when new build is pushed

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/wings#74]
Right now this process has to be done manually.
Ideally we would like to have a continuous integration framework where every new push in WINGS it would run some tests and create and push a new docker image.

**Comment by sirspock** [comment]
wings-base has configured [Docker automatic builds](https://cloud.docker.com/u/kcapd/repository/registry-1.docker.io/kcapd/wings-base/timeline). However, it has no tests.

**Comment by IKCAP** [comment]
That build is configured for the wings-docker, and so this issue should
ideally go there. There is a problem with the auto build in that it doesn't
build every time the wings repo is updated. That needs to be fixed.

**Comment by sirspock** [comment]
Ok, I get it. One choice is to move the wings-docker repo to this repo as a folder. However, this action can break some things (tutorials).

**Comment by sirspock** [comment]
Now, we have two versions
wings-base:latest -> master branch
wings-base:staging -> staging branch
