### ISSUE TITLE
Problems running docker image.

### ISSUE THREAD

**Issue by NicolasRouquette** [KnowledgeCaptureAndDiscovery/wings#98]
The alternative (A) only says to fetch the image, `kcapd/wings-base`.
There are no instructions to execute that image.

I found some helpful instructions here: https://dgarijo.github.io/Materials/Tutorials/wings-docker/#run

That didn't work out of the box because there is no image: `wings:latest`

I tried with the following modified command:

```
    docker run --interactive \
               --tty \
               --env WINGS_MODE='dind' \
               --volume "${NAME}_vol":/opt/wings \
               --name ${NAME} \
               --publish 8080:8080 \
               ${ARGS} kcapd/wings-base:latest
```

Wings starts but I can't login!

What are the administrator credentials that have been configured in this image?

- Nicolas.

**Comment by dgarijo** [comment]
Hello,
https://github.com/KnowledgeCaptureAndDiscovery/wings-docker

specifies more in detail how to run the docker image.

the default user pass installed is:
admin
4dm1n!23

I will close the issue, but please reopen if you have questions
